[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next/static"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://cosmfolio-backend.onrender.com"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCbGyeuz0EXzh7FIblBeaPkqQEmeYS0Un4"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "cosmo-folio-62c7f.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "cosmo-folio-62c7f"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
